[package]
name = "fmby_events"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fmby_core = { path = "../fmby_core" }
fmby_entities = { path = "../fmby_entities" }
poise.workspace = true
sea-orm.workspace = true
tracing.workspace = true
